# Generated by Django 4.1.2 on 2022-11-26 19:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TopicMessages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("qos", models.IntegerField()),
                ("topic", models.TextField()),
                ("fetch_date", models.DateField(default=datetime.date.today)),
                ("message", models.TextField()),
            ],
        ),
    ]
