# Generated by Django 4.1.2 on 2022-11-26 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boxes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="topicmessages",
            name="fetch_date",
            field=models.DateField(default="2022-11-26 21:05:05"),
        ),
    ]
