# Generated by Django 4.1.2 on 2022-12-03 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boxes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TimeOfDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                ("time", models.TimeField()),
            ],
        ),
    ]
