# Generated by Django 4.1.2 on 2022-11-26 20:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boxes", "0002_alter_topicmessages_fetch_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="topicmessages",
            name="fetch_date",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
