# Generated by Django 4.1.2 on 2022-12-10 19:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("boxes", "0002_timeofday_alter_item_color"),
    ]

    operations = [
        migrations.CreateModel(
            name="Organizer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                (
                    "serial_number",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Serial Number"
                    ),
                ),
                (
                    "column_a",
                    models.JSONField(blank=True, default=dict, verbose_name="Column A"),
                ),
                (
                    "column_b",
                    models.JSONField(blank=True, default=dict, verbose_name="Column B"),
                ),
                (
                    "column_c",
                    models.JSONField(blank=True, default=dict, verbose_name="Column C"),
                ),
                (
                    "column_d",
                    models.JSONField(blank=True, default=dict, verbose_name="Column D"),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_boxes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "users",
                    models.ManyToManyField(
                        blank=True, related_name="boxes", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
    ]
