# Generated by Django 4.1.2 on 2022-12-16 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boxes", "0003_organizer"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizer",
            name="column_e",
            field=models.JSONField(blank=True, default=dict, verbose_name="Column E"),
        ),
    ]
